server:
  port: 3000
  prefix: 'api/v1'

db:
  type: 'postgres'
  port: 5432
  database: 'youmix'

redis:
  host: 'localhost'
  port: 6379

jwt:
  expiresIn: 300 # 5 minutes
  refreshTokenExpiresIn: 864000 # 10 days

aws:
  bucketName: # aws s3 bucket name
  region: # aws region
  accessKey: # aws iam accessToken
  secretAccessKey: # aws iam secret access key

sentry:
  dsn: #sentry dsn url
  tracesSampleRate: 1.0
  debug: false

mailer:
  mailgun:
    api_key: # mailgun api key
    domain: # domain configured in mailgun